background {
    monitor =
    path = ~/Pictures/wallpaper.png
    color = rgba(17, 17, 17, 1.0)
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.6
    dots_fade_time = 200
    outer_color = rgb(255, 102, 0)
    inner_color = rgb(17, 17, 17)
    font_color = rgb(255, 102, 0)
    fade_on_empty = false
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(255, 102, 0)
    font_size = 64
    font_family = Sans Bold
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:5000] echo "󰁹 $(cat /sys/class/power_supply/BAT0/capacity)%"
    color = rgb(255, 102, 0)
    font_size = 14
    font_family = Sans
    position = -100, -150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:5000] echo "󰖩 $(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)"
    color = rgb(255, 102, 0)
    font_size = 14
    font_family = Sans
    position = 100, -150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "󰕾 $(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2 * 100"%"}')"
    color = rgb(255, 102, 0)
    font_size = 14
    font_family = Sans
    position = 0, -150
    halign = center
    valign = center
}
